### ISSUE TITLE
[feature] Applying Singleton design to global constant 

### ISSUE THREAD

**Issue by kkong101** [kkong101/binance-future-trade-bot#1]
# Title
`Applying Singleton design to global constant file`

# TODO LIST
- [ ] Exchange global constant to encapsulated class
- [ ] Call all const by getInstance 
- [ ] Applying All const from const class
